name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials:
          # https://github.com/cycjimmy/semantic-release-action#private-packages
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew :patches:buildAndroid clean
          FILE=$(find /home/runner/work/revanced-patches-fork/revanced-patches-fork/patches/build/libs -type f -regex '.*patches-[0-9]+\.[0-9]+\.[0-9]+\.rvp$')
          echo $FILE
          FILE2=$(find ./patches/build/libs -type f -regex '.*patches-[0-9]+\.[0-9]+\.[0-9]+\.rvp$')
          echo $FILE2
          if [[ -z "$FILE" ]]; then
            echo "No matching files found"
            exit 1
          fi
          echo "File found: $FILE"
          echo "filtered_file=$FILE" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ vars.GPG_FINGERPRINT }}
          
      - name: Filter and Upload Artifact
        run: |
          FILE=$(find patches/build/libs -type f -regex '.*patches-[0-9]+\.[0-9]+\.[0-9]+\.rvp$')
          if [[ -z "$FILE" ]]; then
            echo "No matching files found"
            exit 1
          fi
          echo "File found: $FILE"
          echo "filtered_file=$FILE" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: updated-patches
          path: ${{ env.filtered_file }}
          if-no-files-found: error
          retention-days: 20

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm exec semantic-release
